# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapterid', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('sectiontitle', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sectionid', models.IntegerField(default=0)),
                ('subsectioncode', models.IntegerField(default=0)),
                ('subsectiontitle', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subsectionid', models.IntegerField(default=0)),
                ('subsubsectioncode', models.IntegerField(default=0)),
                ('subsubsectiontitle', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubSectionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subsubsectionid', models.IntegerField(default=0)),
                ('subsubsectionitemcode', models.IntegerField(default=0)),
                ('subsubsectionitemtitle', models.TextField(default='')),
            ],
        ),
    ]
