# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chapter_section_subsection_subsubsection_subsubsectionitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='Judgements',
        ),
        migrations.DeleteModel(
            name='Laws',
        ),
        migrations.DeleteModel(
            name='Maxims',
        ),
        migrations.DeleteModel(
            name='Precedence',
        ),
        migrations.DeleteModel(
            name='Principles',
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.DeleteModel(
            name='Ratio',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
