# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_laws_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackageAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageid', models.IntegerField(default=0)),
                ('deviceid', models.IntegerField(default=0)),
                ('resourceid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageid', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='tablename',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
