# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170322_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=1000)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('voucher_code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
