# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=200)),
                ('recepient', models.CharField(max_length=2400)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=20)),
                ('recepient', models.CharField(max_length=2400)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
