# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sections_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageid', models.IntegerField(default=0)),
                ('updateid', models.CharField(max_length=1000)),
                ('viewmodels', models.TextField(default='')),
                ('generateddate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
