# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_packageinfo_useraccesslist_usergroup_usergrouplist_userrole_uservalidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='otherref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='packageinfo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='reference',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
