from ajax import *
from annotations import *
from categories import *
from login import *
from main import *
from notes import *
from signup import *
from profile import *
from payment import *